server:
  port: 8082
eureka:
  client:
    service-url:
      #ע�����ĵ�ַ
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    #������ע�����ĵ����� ��ͬ�������Ʋ����ظ�
    name: cloud-provider
