server:
  port: 8080
eureka:
  instance:
    hostname: eureka
  client:
    #是否向注册中心注册地址
    register-with-eureka: false
    fetch-registry: false
    #读取超时
    eureka-server-read-timeout-seconds: 8
    #连接超时
    eureka-server-connect-timeout-seconds: 8
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    #是否开启自我保护机制
    enable-self-preservation: false

